### ISSUE TITLE
Working on Lisp bindings - unable to get modifiers in events

### ISSUE THREAD

**Issue by stacksmith** [termbox/termbox#14]
While testing the Lisp bindings, I find that I am unable to get modifiers in the event structure.  Even in `stty raw` the control characters are processed and alt is ignored (except when the terminal grabs it).  Forgive me for asking before checking it in C - I hope you can advise me before I waste time in case it's normal behaviour and I should do something with `stty`.

I was assuming that the termbox environment provides raw input by default.  

What is the recommended way to get clean input events?  

Thank you

**Comment by adsr** [comment]
Indeed termbox should be setting raw mode for you. Can you write a minimal repro program?

**Comment by adsr** [comment]
Feel free to reopen on https://github.com/termbox/termbox2 if it's still an issue.
