### ISSUE TITLE
Add dvtm to the list of supported terminals

### ISSUE THREAD

**Issue by tdukv** [termbox/termbox#15]
Dvtm is a simple dynamic terminal multiplexer.
https://www.brain-dump.org/projects/dvtm/

**Comment by adsr** [comment]
dvtm appears to be in terminfo[0] so it should already work. Do you think dvtm should be a built-in?

It would actually be good to verify that the built-in terminals are indeed the most popular ones. I'm not sure where we might find that info.

By the way, I encourage you to check out termbox2[1]. It's very simple to add a built-in terminal in termbox2. Add an entry like this[2] and then run `make terminfo`. (Requires terminfo to be installed.)

[0] https://invisible-island.net/ncurses/terminfo.src.html#toc-_Dvtm
[1] https://github.com/termbox/termbox2
[2] https://gist.github.com/adsr/99a47f19f843aa5e1333a055b4303f55

**Comment by tdukv** [comment]
Nevermind, I had the terminfo messed up on my side so I thought it was incorrectly marked as unsupported.
