### ISSUE TITLE
Add support for more inputs: ctrl+shift, shift+arrow, etc

### ISSUE THREAD

**Issue by adsr** [termbox/termbox#3]

**Comment by colinta** [comment]
Actually shift+arrow is supported - at least, I'm getting those events (using the Swift-Termbox bridge https://github.com/dduan/Termbox - my fork uses an enum for the key events: https://github.com/colinta/Termbox)

**Comment by adsr** [comment]
termbox2 supports a whole bunch of these. https://github.com/termbox/termbox2/blob/b4f28dc9e4b0f0bad0059171db1a335f1f554150/termbox.h#L849
