### ISSUE TITLE
Investigate refactoring to avoid relying on VMIN and VTIME

### ISSUE THREAD

**Issue by adsr** [termbox/termbox#6]
See https://github.com/adsr/mle/issues/47

**Comment by osa1** [comment]
You could set stdin to non-blocking mode, using something like

```c
int old_stdin_flags = fcntl(STDIN_FILENO, F_GETFL);
fcntl(STDIN_FILENO, F_SETFL, old_stdin_flags | O_NONBLOCK);
```

**Comment by adsr** [comment]
termbox2 sets `VMIN=1 VTIME=0` so we avoid the WSL bug above. It's also written in a way that avoids an extra `select(2)` call.
